<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-ITSupportAzureApp-6fc00f67-cd82-4528-aa21-70957b186e71</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.29" />
  </ItemGroup>

</Project>
